# Neural Network From Scratch
## imports

In [19]:
import numpy as np
np.core.arrayprint._line_width = 80

## data

In [20]:
def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y

## layers

In [25]:
class Activation:
    def __init__(self, activation):
        self.activation = activation
    
    def forward(self, x):
        if self.activation == 'step':
            self.output = np.sign(x)

        if self.activation == 'linear':
            self.output = x

        if self.activation == 'sigmoid':
            self.output = np.sin(x)

        if self.activation == 'relu':
            self.output = np.maximum(0, x)
        
        if self.activation == 'softmax':
            exp_values = np.exp(x - np.max(x, axis=1, keepdims=True))
            prob_values = exp_values/np.sum(exp_values, axis=1, keepdims=True)
            self.output = prob_values

In [23]:
class Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))


    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [8]:
def process_layer(inputs, weights, biases):
    #return np.dot(np.array(weights).T, inputs) + bias
    return np.dot(inputs, np.array(weights).T) + biases

def initialise_weights(layer_sizes, input_size=None):
    if input_size != None:
        layer_sizes.insert(0,input_size)
    
    weights = []
    for i in range(len(layer_sizes)):
        if i == 0:
            continue
        weights.append(np.random.randn(layer_sizes[i], layer_sizes[i-1]))

    return weights

## loss functions

In [ ]:
# categorical cross-entropy


## implementation

In [30]:
np.random.seed(0)
X, y = spiral_data(100, 3)

dense1 = Dense(2, 3)
activation1 = Activation('relu')

dense2 = Dense(3, 3)
activation2 = Activation('softmax')

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])


[[0.33333333 0.33333333 0.33333333]
 [0.33331734 0.33331832 0.33336434]
 [0.3332888  0.33329153 0.33341967]
 [0.33325941 0.33326395 0.33347665]
 [0.33323311 0.33323926 0.33352763]]


In [36]:
softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]

loss = -(math.log(softmax_output[0]))

print(loss)

0.35667494393873245
